---
# ansible_role_system_upgrade/tasks/dnf.yml
# Author: MTO 
# Description: DNF file for ansible_role_system_upgrade
#
- name: "UPDATE - Ensure Dependencies are present."
  package:
    name: dnf-utils
    state: present

- name: "UPDATE - Mark packages on hold."
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'exclude={{ item }}'
    state: present
  with_items: "{{ system_upgrade_packages_on_hold }}"

- name: "UPDATE - Store List of Updates for further Inspection."
  command: dnf check-update
  args:
    warn: false
  register: system_upgrade_update_list_dnf
  failed_when: system_upgrade_update_list_dnf.rc > 100
  ignore_errors: 'true'

- name: "UPDATE - All."
  dnf:
    name: "*"
    state: latest
  when: 
    - system_upgrade_all | bool
  tags:
    - all 

- name: "UPDATE - Security"
  dnf:
    name: "*"
    state: latest
    security: true
  when: 
    - system_upgrade_security | bool
  ignore_errors: yes
  tags:
    - securtiy

- name: "UPDATE - Bugfix"
  yum:
    name: "*"
    state: latest
    bugfix: true
  when: 
    - system_upgrade_bugfix | bool
  ignore_errors: yes
  tags:
    - bugfix

- name: "UPDATE  - Update only"
  yum:
    name: "*"
    state: latest
    update_only: true
  when: 
    - system_upgrade_only | bool
  ignore_errors: yes
  tags:
    - only

- name: "UPDATE - Cleanup."
  dnf:
    autoremove: 'yes'

- name: "UPDATE - Unhold packages."
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'exclude={{ item }}'
    state: absent
  with_items: "{{ system_upgrade_packages_on_hold }}"

- name: "UPDATE - Check for reboot hint."
  shell: dnf needs-restarting -r
  args:
    warn: false
  register: reboot_hint_dnf
  failed_when: reboot_hint_dnf.rc >= 2
  changed_when: reboot_hint_dnf.rc == 1

- name: "UPDATE - Set Reboot Hint."
  set_fact:
    reboot_hint: true
  when: reboot_hint_dnf.rc == 1