---
# ansible_role_system_upgrade/tasks/dnf_upgrade.yml
# Author: MTO 
# Description: Upgrade file for ansible_role_system_upgrade
#
- name: "UPGRADE - Install dnf-plugin-system-upgrade"
  dnf:
    name: dnf-plugin-system-upgrade
    state: present

- name: "UPGRADE - Download"
  shell: dnf system-upgrade download -y --allowerasing --best --releasever="{{ system_upgrade_release_version }}"
  ignore_errors: true
  warn: false  

- include: reboot.yml
  vars:
    reboot_command: dnf system-upgrade reboot
    timeout: 7200